name: visionflow_app
description: "Aplicativo mobile do projeto VisionFlow - Óculos assistivo inteligente para pessoas com deficiência visual."
publish_to: 'none'

version: 0.3.0+3

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # Interface e Acessibilidade
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3

  # Bluetooth Low Energy (BLE)
  flutter_blue_plus: ^1.32.0

  # Gerenciamento de Estado
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Utilitários
  permission_handler: ^11.3.1
  get_it: ^7.7.0
  logger: ^2.4.0

  # Animações
  flutter_animate: ^4.5.0

  # Gráficos e persistência
  fl_chart: ^0.69.0
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1 

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon/
    - assets/images/glasses_hero.png
    - assets/images/glasses_device.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon/icon.png"
  min_sdk_android: 21